language: python

python:
#  - 3.4
  - 3.5
#  - 3.6


services:
  - docker

script:
  # Run trans server on Docker
  - docker run -d -p 8080:80 nwtgck/trans-server-akka:v1.4.0

  # Install trans-cli from GitHub
  - pip3 install --upgrade git+https://github.com/nwtgck/trans-cli-python.git@$TRAVIS_BRANCH

  # Set server URL to localhost trans server
  - trans-cli server-url "http://localhost:8080"

  #  Create random 10MB file
  - dd if=/dev/urandom of=10MB.file bs=1024 count=10240

  # Send 10MB.file
  - trans-cli send 10MB.file > file_id.txt

  # Get the file
  - trans-cli get `cat file_id.txt`

  # Diff
  - diff 10MB.file `cat file_id.txt`

  # Delete the file
  - trans-cli delete `cat file_id.txt`




cache:
  - apt
  - directories:
    - $HOME/.cache/pip