language: python

python:
#  - 3.4
  - 3.5
#  - 3.6


services:
  - docker

script:
  # Run trans server on Docker
  - docker run -d -p 80:80 nwtgck/trans-server-akka:v1.4.0

  # Install trans-cli from GitHub
  - pip3 install --upgrade git+https://github.com/nwtgck/trans-cli-python.git@$TRAVIS_BRANCH
  # Show help of trans-cli
  - trans-cli


cache:
  - apt
  - directories:
    - $HOME/.cache/pip